packages:
  - name: docling
    functions:
      - name: convert
        runtime: python:3.11
        limits:
          timeout: 300000  # 5 minutes for document processing
          memory: 1024     # Max memory for DO function
        environment:
          LOG_LEVEL: INFO
