packages:
  - name: docling
    functions:
      - name: convert
        runtime: python:3.11
        limits:
          timeout: 300000  # 5 minutes for document processing
          memory: 2048     # 2GB memory for ML models
        environment:
          LOG_LEVEL: INFO
