name: docling-nest
region: nyc

functions:
  - name: docling
    git:
      repo_clone_url: https://github.com/brandnewbox/docling-nest.git
      branch: main

    source_dir: /

    envs:
      - key: LOG_LEVEL
        value: INFO
        scope: RUN_TIME
        type: GENERAL
